context:
  version: 0.2.0

package:
  name: compose-language-service
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@microsoft/compose-language-service/-/compose-language-service-${{ version }}.tgz
  sha256: 56aa27237794cf45290e7a13448a998a71dfca6582e29ae9b464b6b63fed9833

build:
  number: 0
  noarch: generic

requirements:
  host:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - "docker-compose-langserver 2>&1 | grep -q \"Connection input stream is not set.\""

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Language service for Docker Compose documents
  homepage: https://github.com/microsoft/compose-language-service
  repository: https://github.com/microsoft/compose-language-service

extra:
  recipe-maintainers:
    - danielnachun
