context:
  version: "0.5.0"

package:
  name: compose-language-service
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@microsoft/compose-language-service/-/compose-language-service-${{ version }}.tgz
  sha256: 2d6af41c4aabaa5c4fc89d2293eae6b561fc37b2c663a504000383394f715700

build:
  number: 0
  noarch: generic

requirements:
  host:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - "docker-compose-langserver 2>&1 | grep -q \"Connection input stream is not set.\""

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Language service for Docker Compose documents
  homepage: https://github.com/microsoft/compose-language-service
  repository: https://github.com/microsoft/compose-language-service

extra:
  recipe-maintainers:
    - danielnachun
